### ISSUE TITLE
Not working on TFS on premise 

### ISSUE THREAD

**Issue by NoOneAtHome** [onlyutkarsh/ExportAsPDF#1] opened 2016-05-03 23:17 UTC
I recently upgrade our on prem TFS 2015 with Update 2.  Downloaded and installed.
After right clicking a build, clicking Export as PDF and selecting the sections to include nothing happens when I click on Export as PDF button or Cancel button.  I have to click the 'x' in the dialog to close the pop up. 

it is throwing a security error on here: 
   var appInsights = window.appInsights || function (config) {
            function r(config) { t[config] = function () { var i = arguments; t.queue.push(function () { t[config].apply(t, i) }) } } var t = { config: config }, u = document, e = window, o = "script", s = u.createElement(o), i, f; for (s.src = config.url || "//az416426.vo.msecnd.net/scripts/a/ai.0.js", u.getElementsByTagName(o)[0].parentNode.appendChild(s), t.cookie = u.cookie, t.queue = [], i = ["Event", "Exception", "Metric", "PageView", "Trace"]; i.length;) r("track" + i.pop()); return r("setAuthenticatedUserContext"), r

**Comment by onlyutkarsh** [comment] 2016-05-04 08:09
@NoOneAtHome thanks for reporting this. I think few of the SDK components are changed in Update 2 causing extension to break. I will investigate.

**Comment by larrysteele** [comment] 2016-05-06 15:57
I am also experiencing this issue. As soon as I select the options and Export as PDF, nothing happens and I have to "x" out of the window.

**Comment by onlyutkarsh** [comment] 2016-05-06 18:50
@larrysteele Apologies for the inconvenience. I am working on fixing this issue.

**Comment by larrysteele** [comment] 2016-05-06 18:53
Thank you. I'd also like to recommend that it would be also great to have this same functionality in the Release Hub. Regards!

**Comment by NoOneAtHome** [comment] 2016-06-14 19:01
@onlyutkarsh Any update on a fix?

**Comment by onlyutkarsh** [comment] 2016-06-14 21:50
@NoOneAtHome Missed providing an update on this one. I have a repro and issue is due to few changes in the SDK after update 2. I am currently working with MS product team to identify the root cause (on whether the issue with the SDK or the API calls from the extension). I will provide the fix as soon as I get some more information from them. Sorry for the inconvenience.

**Comment by onlyutkarsh** [comment] 2016-06-24 23:21
@NoOneAtHome this is fixed now in the latest version available on the marketplace. Can you please download and try? Let me know if it fixes the issue for you.

**Comment by onlyutkarsh** [comment] 2016-06-26 12:47
@NoOneAtHome Few other users who had the same issue responded that it is fixed for them. I am closing this for now. Do let me know if it is not the case for you.

**Closed as completed by onlyutkarsh** 2016-06-26 12:47 UTC
Labels: bug, fixed
